remote_theme: mmistakes/minimal-mistakes@4.24.0

title: "Amichay Feldman"
description: "AI researcher & engineer"
url: "https://amichayfeldman.github.io"

author:
  name: "Amichay Feldman"

plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-github-metadata
